;; packages
(source gnu)
(source melpa)
(source marmalade)

;; requires
;;; ui
(depends-on "auto-highlight-symbol")
(depends-on "highlight-symbol")
;;(depends-on "color-theme")
(depends-on "whitespace")
(depends-on "hlinum")
(depends-on "volatile-highlights")
(depends-on "indent-guide")

;;; helm
(depends-on "helm")
(depends-on "quickrun")
(depends-on "helm-swoop")
(depends-on "imenus")
(depends-on "ido-occasional")
(depends-on "ido-vertical-mode")

;;; utils
(depends-on "init-loader")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "dirtree")
(depends-on "recentf")
(depends-on "undo-tree")
(depends-on "smartparens")
(depends-on "anzu")
(depends-on "flymake")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "flycheck-pos-tip")

;;; modes
(depends-on "js2-mode")
(depends-on "web-mode")
(depends-on "python-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "dockerfile-mode")
