(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-x\9" 'delete-window)
(global-set-key "\C-x\1" 'delete-other-windows)
(global-set-key "\C-x\2" 'split-window)
(global-set-key "\C-x\3" 'split-window-vertically)
(global-set-key (kbd "C-]") 'cua-set-rectangle-mark)
(global-set-key "\C-\\" 'undo)
(global-set-key "\C-x\j\l" 'goto-line)
(global-set-key "\C-x\C-c" 'save-buffers-kill-terminal)
(global-set-key "\C-i" 'indent-region)
(global-set-key "\C-x\C-i" 'indent-region)
(global-set-key (kbd "C-x <left>")  'windmove-left)
(global-set-key (kbd "C-x <down>")  'windmove-down)
(global-set-key (kbd "C-x <up>")    'windmove-up)
(global-set-key (kbd "C-x <right>") 'windmove-right)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x C-g C-h") 'highlight-symbol)
(global-set-key (kbd "C-x C-g C-n") 'highlight-symbol-next)
(global-set-key (kbd "C-x C-g C-p") 'highlight-symbol-prev)
(global-set-key (kbd "C-x C-g C-d") 'highlight-symbol-remove-all)
(global-set-key
 (kbd "C-x C-w")
 'wsl-copy)
(global-set-key
 (kbd "C-x C-y")
 'copy-wsl)
